---
title: The Host
timezone: UTC
collections:
  artists:
    title: Artists
    output: true
  episodes:
    title: Episodes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: artists
  values:
    website: 
    imdb: 
    instagram: 
    twitter: 
- scope:
    path: ''
    type: episodes
  values:
    image: 
    pinecast-url: 
masthead-image: "/uploads/the-host-logo__microphone-med.jpg"
email: thehostpodsubmissions@gmail.com
description: The Host is a fictional late-night call-in show for the fringes of reality.
  Think Welcome to Night Vale meets Dr. Frasier Crane.
baseurl: 
url: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
